# Configuração básica do Air
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main"
bin = "tmp/main"
full_bin = "tmp/main"
watch_dir = "."
exclude_dir = ["tmp", "vendor"]
include_ext = ["go"]
exclude_file = []
delay = 1000
log = "stdout"
